services:
  knorr:
    hostname: knorr
    build: .
    ports:
      - "3001:3333"
    environment:
      PYTHONUNBUFFERED: 1

  lenor:
    hostname: lenor
    build: .
    ports:
      - "3002:3333"
    environment:
      PYTHONUNBUFFERED: 1

  knorr-client:
    build: 
      context: .
      dockerfile: Dockerfile-client
    depends_on:
      - knorr
    environment:
      PYTHONUNBUFFERED: 1